Feat/hng 12 super admin nav bar component
hngprojects/hng_boilerplate_nextjs pull request #235
Opened 2024-07-18 19:34 UTC by taiwonaf

- Created Super admin nav bar component
- Created admin layout component
- created admin route (/admin)

2024-07-18 20:44 UTC, michaelhpet requested changes

2024-07-18 20:44 UTC, michaelhpet commented on tailwind.config.ts
> +        error: "#F81404",
Please use variables

2024-07-18 20:56 UTC, taiwonaf commented on tailwind.config.ts
> +        error: "#F81404",
done

2024-07-19 10:28 UTC, michaelhpet requested changes

2024-07-19 10:28 UTC, michaelhpet commented on src/app/globals.css
> +    --error: #F81404;
use hsl values like the variables above

2024-07-19 10:39 UTC, taiwonaf commented on src/app/globals.css
> +    --error: #F81404;
resolved

2024-07-19 10:53 UTC, michaelhpet approved these changes

2024-07-19 16:02 UTC, merged