Feat/231 user dashboard settings layout
hngprojects/hng_boilerplate_nextjs pull request #239
Opened 2024-07-18 20:03 UTC by incredible-phoenix246

# Description

**Closes #issue_number_here**

# Changes proposed
Fixed general user settings layout

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
- [] I am making a pull request against the **dev branch** (left side).
- [] My commit messages styles matches our requested structure.
- [] My code additions will fail neither code linting checks nor unit test.
- [] I am only making changes to files I was requested to.

# Screenshots/Videos
![Screenshot_2024-07-18_21-02-20](https://github.com/user-attachments/assets/0434904f-e6ec-4b3e-9471-e17bdc4a4369)
![Screenshot_2024-07-18_21-01-57](https://github.com/user-attachments/assets/d8506fc0-1b5e-4734-a6fa-4acf9717ca52)

2024-07-18 20:07 UTC, incredible-phoenix246 commented
@ickynavigator here is the update included the changes u asked for

2024-07-18 20:25 UTC, michaelhpet requested changes

2024-07-18 20:25 UTC, michaelhpet commented on src/components/common/settings/sidebar.tsx
> +  // remove the /settings/ from the pathname
Please don't write unnecessary comments

2024-07-18 20:25 UTC, michaelhpet commented on src/components/common/settings/sidebar.tsx
> +const Settings_Sidebar_Links: SettingsSidebarProperties[] = [
Is this pascal-kebab case? Either use camelCase `settingsSidebarLinks` or use `SETTINGS_SIDEBAR_LINKS` since it looks like a constant

2024-07-18 20:25 UTC, michaelhpet commented on src/components/common/settings/sidebar.tsx
> +type SettingsSidebarProperties = {
This type and the type anotation below isn't needed. TypeScript will infer the properties.

2024-07-18 20:30 UTC, incredible-phoenix246 commented
@michaelhpet updated

2024-07-18 20:31 UTC, michaelhpet approved these changes

2024-07-20 08:46 UTC, closed without merging

2024-07-20 08:47 UTC, oreoluwa212 commented
Update your branch to match dev and make a PR asap please. ensure lint and test passes