feat(HNG-39): external static pages > navbar component
hngprojects/hng_boilerplate_nextjs pull request #299
Opened 2024-07-19 22:54 UTC by henrymishael

# Description

**Closes #39**

# Changes proposed
-- Create a navbar component that displays the app logo, navigation links, and login and get started buttons.
-- This component should have props to allow for a logged in and logged out state (meaning, the login and get started buttons should only be shown when the user is not logged in)
-- This component should allow for mobile responsiveness.
-- Write unit tests for this component to model expected behavior.

## What were you told to do?

-- Create a navbar component
-- Account for authenticated state by removing the login and getting started buttons when user is logged in and showing the -- 
    notification and profile.
-- Integrate the shadcn button component for the buttons on the component.
-- Make the navbar responsive for mobile devices.
-- Write unit tests to ensure the component works as expected.

#[FEAT] External Static Pages > Navbar component 

## What did you do?

created a index.tsx file in layouts/navbar
created a logo component in components/common
created a Provider.tsx file in components for session wrapper to display the authenticated header view
created a Navbar.test.tsx file in test folder

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
- [] I am making a pull request against the **dev branch** (left side).
- [] My commit messages styles matches our requested structure.
- [] My code additions will fail neither code linting checks nor unit test.
- [] I am only making changes to files I was requested to.

# Screenshots/Videos

![Screenshot 2024-07-19 145301](https://github.com/user-attachments/assets/110a3a55-dd38-4c5e-a604-3919e082440f)
![Screenshot 2024-07-19 145530](https://github.com/user-attachments/assets/7cad1387-12af-4ba6-86b7-980f1661279d)

2024-07-19 23:16 UTC, oreoluwa212 commented on src/components/common/Logo/logo.tsx
> +// eslint-disable-next-line react/prop-types
remove comment

2024-07-19 23:28 UTC, henrymishael commented on src/components/common/Logo/logo.tsx
> +// eslint-disable-next-line react/prop-types
okay
that's eslint though

2024-07-19 23:38 UTC, oreoluwa212 requested changes
remove comment

images
Also, export svg as an image and import into tsx file

Layout>index.tsx
Wrong file path, you do not need to use your component at all. It is for others

remove imports fom vitest, they are global now

2024-07-19 23:38 UTC, oreoluwa212 commented on src/components/common/Logo/logo.tsx
> +          <path
extract your svgs

2024-07-19 23:38 UTC, oreoluwa212 commented on src/components/layouts/index.tsx
> +import React from "react";
Wrong file path, you do not need to use your component at all. It is for others

2024-07-19 23:38 UTC, oreoluwa212 commented on src/test/Navbar.test.tsx
> +// vi.mock("next/image", () => ({
remove comments please

2024-07-20 07:09 UTC, oreoluwa212 approved these changes

2024-07-20 07:09 UTC, merged