feat : implemented password update successful modal, as well as testi…
hngprojects/hng_boilerplate_nextjs pull request #303
Opened 2024-07-19 23:40 UTC by Maiqel1

…ng and instructions for use in guides

# Description

**Closes #172 **

# Changes proposed

## What were you told to do?
Implement the Password successful modal

## What did you do?
i implemented the password update successful modal, as well as a file for testing. i used tailwind css and shadcn components for styling

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos
![Create Next App - Google Chrome 7_18_2024 10_20_12 PM](https://github.com/user-attachments/assets/0cc762a9-2058-4e43-bbcc-ae43fca63baa)

2024-07-19 23:55 UTC, Justfemi reviewed
Don't edit the src/guides/page.tsx file
Use [shadcn](https://ui.shadcn.com/docs/components/dialog) for the modal

2024-07-19 23:55 UTC, Justfemi commented on src/app/guides/page.tsx
You're not supposed to edit this file

2024-07-20 00:21 UTC, PrudentBird submitted a review, later dismissed

2024-07-20 00:21 UTC, PrudentBird commented on src/app/guides/page.tsx
Remove edits on guides/page.tsx

2024-07-20 00:35 UTC, Justfemi requested changes, later dismissed
Use [shadcn ](https://ui.shadcn.com/docs/components/dialog)for your modal

2024-07-20 01:27 UTC, Maiqel1 commented
@Justfemi

2024-07-20 06:51 UTC, oreoluwa212 approved these changes

2024-07-20 06:54 UTC, merged