Feat/206 product details component
hngprojects/hng_boilerplate_nextjs pull request #336
Opened 2024-07-20 10:48 UTC by GreyyDaze

# Description
**Closes #206**

# Changes proposed

## What were you told to do?
[Feature]: [FEAT] User Dashboard Product Details Component

## What did you do?
- Developed the Product Details Component, including a header with the product name, a close button, and an image container.
- Added fields for Product ID, Category, Date added, Stock, and Price, along with a section for the product description.
- Implemented Edit and Delete buttons, ensuring functionality for displaying and dismissing product details.
- Optimized the component for responsive design, including error handling for missing data and smooth transitions for opening and closing views.
- Added appropriate alt text for the product image and ensured text formatting, with preparations for future Edit and Delete functionalities.

# Check List (Check all the applicable boxes)
- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos
![image](https://github.com/user-attachments/assets/798e175c-f207-41b0-85b8-781bddac2f3e)
after clicking close button
![image2](https://github.com/user-attachments/assets/5a79b53e-383c-4b81-8e2f-be6174f972f7)

2024-07-20 18:48 UTC, skeby commented on public/product_image.jpg
put this image inside the images folder asap `public/images/{yourpagename}/product_image.jpg`
put the icons folder inside {yourpagename} folder `public/images/{yourpagename}/icons`

2024-07-20 18:50 UTC, skeby commented on src/components/common/ProductDetailsCard/ProductDetailsCard.tsx
> +    if (productID === "N/A") {
Remove all console.logs

2024-07-20 18:54 UTC, skeby submitted a review, later dismissed

2024-07-20 18:54 UTC, skeby commented on src/components/common/ProductDetailsCard/ProductDetailsCard.tsx
> +    event.stopPropagation(); // Prevent event bubbling
Remove all comments asap

2024-07-20 20:32 UTC, GreyyDaze commented on public/product_image.jpg
fix

2024-07-20 20:35 UTC, GreyyDaze commented on src/components/common/ProductDetailsCard/ProductDetailsCard.tsx
> +    if (productID === "N/A") {
fix

2024-07-20 20:36 UTC, GreyyDaze commented on src/components/common/ProductDetailsCard/ProductDetailsCard.tsx
> +    event.stopPropagation(); // Prevent event bubbling
fix

2024-07-21 06:58 UTC, PrudentBird requested changes

2024-07-21 06:58 UTC, PrudentBird commented on public/images/productdetails/icons/close.svg
Use lucide react

2024-07-21 07:38 UTC, GreyyDaze commented on public/images/productdetails/icons/close.svg
fix

2024-07-21 07:47 UTC, PrudentBird approved these changes

2024-07-21 07:48 UTC, PrudentBird commented
Fix your tests so I can merge

2024-07-21 07:54 UTC, GreyyDaze commented
@PrudentBird Mentor, I have fixed test cases.

2024-07-21 07:56 UTC, merged