Feat/hng 213 component media file upload
hngprojects/hng_boilerplate_nextjs pull request #338
Opened 2024-07-20 10:58 UTC by Peliah

# Description

Create a reusable Media file upload component with drag-and-drop functionality using TypeScript (TSX) and Shadcn in a Next.js application. The component should support file selection through drag-and-drop and manual file input, displaying previews of the uploaded files with an option to delete uploaded images. It should also include a label prop and a customizable button component

**Closes #213**

# Changes proposed

## What were you told to do?
. Create a component with a drag and drop functionality to insert images
. Include a button for manual file selection
. The component should handle multiple file uploads
. Pass the files (uploaded/deleted) files through the parent component
. Add a customizable button component as prop
. Also include a label prop

## What did you do?

created the MediaFileUpload component in the src/component/layout directory 
Created  function to upload a file,
Created the function to delete a file
created where i passed these values as props
I included the label as prop
I ran the command `pnpm dlx shadcn-ui@latest add button` to download the shadcn button located the the /src/component/ui directory
I added the index.test.tsx file for tests in my directory

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos

![Screenshot from 2024-07-20 00-46-09](https://github.com/user-attachments/assets/c93b7b59-617d-4679-9eef-0b9b6a6bcc45)
[Screencast from 07-20-2024 12:45:01 AM.webm](https://github.com/user-attachments/assets/b509544a-841c-444b-814d-50534bf7a240)

In the parent component where the MediaUpload Component is called i wrote sample to show how to call my component
`      <MediaUpload onFilesAdded={handleFilesAdded}
        onFileDeleted={handleFileDeleted}
        label="Accepts images, videos or 3D models"
        CustomButton={CustomUploadButton}
        />
        `
I also included a sample of the props passed into my component
`
const handleFilesAdded = (files: File[]) => {
    setUploadedFiles((prevFiles) => [...prevFiles, ...files]);
  };

  const handleFileDeleted = (file: File) => {
    setUploadedFiles((prevFiles) => prevFiles.filter((f) => f !== file));
  };
`

And finally my component can and must be used in a client component 
`"use client"`

2024-07-20 19:41 UTC, skeby requested changes
Remove all comments
Move your component out of the layouts subfolder
Move test component to the tests folder

2024-07-21 02:29 UTC, Peliah commented
> Remove all comments Move your component out of the layouts subfolder Move test component to the tests folder

Hi, @skeby I've fixed these problems and awaiting approval

2024-07-21 04:38 UTC, skeby commented on src/test/index.test.tsx
Please name the test file properly (MediaUpload.test.tsx)
Tag me when you've done this

2024-07-21 04:39 UTC, skeby commented on src/test/index.test.tsx
Attach screenshots of your tests and lint

2024-07-21 11:12 UTC, Peliah commented on src/test/index.test.tsx
@skeby Changes requested have been done

2024-07-21 15:24 UTC, Peliah commented
@skeby all requested changes have been made 
Please review

2024-07-22 08:30 UTC, Peliah commented
@JulianaSau please what other changes are required? I've made the previous changes that was requested by @skeby

2024-07-22 08:48 UTC, skeby commented
> @JulianaSau please what other changes are required? I've made the previous changes that was requested by @skeby

I never review your update, you comot your `changed requested` label

2024-07-22 12:46 UTC, skeby approved these changes

2024-07-22 12:47 UTC, skeby commented
@PrudentBird can you merge this when you Abdul gives you access again

2024-07-22 19:12 UTC, mrcoded approved these changes

2024-07-22 19:13 UTC, merged