feat: add Accordion component with chevron icon and test file
hngprojects/hng_boilerplate_nextjs pull request #353
Opened 2024-07-20 12:41 UTC by Confidenceb

# Description

**Closes #46 **

# Changes proposed

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [] My code follows the code style of this project.
- [] This PR does not contain plagiarized content.
- [] The title and description of the PR is clear and explains the approach.
- [] I am making a pull request against the **dev branch** (left side).
- [] My commit messages styles matches our requested structure.
- [] My code additions will fail neither code linting checks nor unit test.
- [] I am only making changes to files I was requested to.

# Screenshots/Videos

![Screenshot 2024-07-20 023213](https://github.com/user-attachments/assets/2290b904-1494-4ad5-95aa-3d13a2c64d42)
![Screenshot 2024-07-20 023154](https://github.com/user-attachments/assets/a3926018-7a79-496b-8511-761d1ee9789c)
![Screenshot 2024-07-20 023123](https://github.com/user-attachments/assets/c15345f5-20d3-4df0-bfac-e7887dfed39a)

2024-07-20 13:09 UTC, JulianaSau commented on src/components/Accordion.tsx
Shadcn already has an accordion component. why are you re-inventing the wheel?
Just install the accordion component, if it's not already there and use that

2024-07-20 14:04 UTC, Confidenceb commented on src/components/Accordion.tsx
I should do it again using Shadcn?

2024-07-20 17:05 UTC, JulianaSau commented on src/components/Accordion.tsx
yes

2024-07-21 07:01 UTC, PrudentBird commented on src/components/Accordion.tsx
Use lucide react chevron down

2024-07-21 07:01 UTC, PrudentBird requested changes
Use lucide react chevron down

2024-07-21 15:21 UTC, Confidenceb commented on src/components/Accordion.tsx
Using the same code or with Shadcn?

2024-07-22 05:48 UTC, JulianaSau commented on src/components/Accordion.tsx
> +export function AccordionDemo() {
name this component appropriately

2024-07-22 05:48 UTC, JulianaSau requested changes, later dismissed

2024-07-22 05:48 UTC, JulianaSau commented on src/components/chevron-down.svg
delete this. use icons from lucide-icons

2024-07-22 10:17 UTC, Confidenceb commented on src/components/chevron-down.svg
okay

2024-07-22 17:50 UTC, Confidenceb reviewed
Done using Shadcn

2024-07-22 17:52 UTC, Confidenceb reviewed
Done

2024-07-22 17:53 UTC, Confidenceb reviewed
Done

2024-07-22 17:53 UTC, Confidenceb commented on src/components/chevron-down.svg
Deleted
Already used the Lucide-icons

2024-07-22 17:55 UTC, Confidenceb reviewed
done

2024-07-22 17:55 UTC, Confidenceb commented on src/components/Accordion.tsx
> +export function AccordionDemo() {
Done
Changed to 
AccordionComponent

2024-07-22 17:57 UTC, Confidenceb reviewed
done

2024-07-22 18:28 UTC, JulianaSau approved these changes

2024-07-22 18:29 UTC, JulianaSau commented
@Confidenceb is your branch up to date with dev?

2024-07-22 18:33 UTC, closed without merging