Feat/32 new template with html
hngprojects/hng_boilerplate_nextjs pull request #360
Opened 2024-07-20 14:08 UTC by kingbary

# [FEAT] Email Templates > SuperAdmin Email Management Dashboard > New Template with HTML

**Closes #32 **

# Changes proposed

## What were you told to do?
 # Create the Page for Generating New Email Template with HTML found in the Super Admin Email Management Dashboard

## What did you do?
Create breadcrumbs for easy navigation
Implement Page with a clear title and description
 Implement Tips component using shadcn-ui alert
 Implement Form input with label and button
 Validate the link from the form input points to the .html file
 Make button generates a template on form submission
 Navigate to the preview template page on successful template generation
 Components adhere to the brand design and colour scheme
 Make Page responsive across device widths

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos
### [Figma file Link](https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=63-69677&m=dev)
<img width="959" alt="generate-email-template-screenshot-1" src="https://github.com/user-attachments/assets/21d6d45e-1a99-4fb3-8f83-53c6fefec558">
<img width="959" alt="generate-email-template-screenshot-2" src="https://github.com/user-attachments/assets/2a7b874c-7076-45d7-9faf-d4e43377ffbf">

### [View screen record](https://www.loom.com/share/83922ccd905f419295b1855a3dbe0ace?sid=053b2559-1059-42c3-8d82-1dc49a1ad67c)

2024-07-20 14:11 UTC, kingbary commented
@chumex412 @Samadeen @shalomtaiwo  Please review the PR

2024-07-20 14:21 UTC, PrudentBird requested changes
Follow all guidelines

2024-07-20 14:21 UTC, PrudentBird commented on .gitignore
Why are you changing git ignore??

2024-07-20 14:21 UTC, PrudentBird commented on .vscode/extensions.json
why are you changing VSCode settings??

2024-07-20 14:21 UTC, PrudentBird commented on package.json
Why are you installing dependencies??

2024-07-20 14:41 UTC, kingbary reviewed
I have updated it now.

2024-07-20 14:41 UTC, kingbary commented on .vscode/extensions.json
Fixed!

2024-07-20 21:56 UTC, oreoluwa212 commented
Checks are failing, fix up!

2024-07-20 22:53 UTC, kingbary commented
I couldn't run the test locally that's why the test failed. I have fixed the error I got the test console now. Please rerun the test

2024-07-21 06:15 UTC, PrudentBird requested changes
Fix up all your errors, you changed config files, go back and remove all the changes !


All your tests are failing!

2024-07-21 09:34 UTC, kingbary commented
I could run the test locally, I fixed all the test errors now. Please review!

2024-07-21 22:11 UTC, oreoluwa212 commented
`Conflicting files
.github/workflows/lint.yml
.github/workflows/staging-cicd.yml
.vscode/extensions.json
.vscode/settings.json
docker/staging/docker-compose.yml
package-lock.json
src/app/(admin)/layout.tsx
src/app/(home)/page.tsx
src/app/globals.css
src/app/guides/page.tsx
src/components/common/Breadcrumb/README.md
src/components/common/Breadcrumb/index.tsx
src/components/layouts/homepage/Hero.tsx
src/components/superadminlayout/navbar/AdminNavbar.tsx
src/components/ui/button.tsx
src/components/ui/dialog.tsx
tsconfig.json`

2024-07-21 22:11 UTC, closed without merging

2024-07-21 22:14 UTC, oreoluwa212 commented
you have to move your folders around, after pulling and retrieve the components that have been done by other interns, we cant accept repetition
N.B you can check the github issues [here](https://github.com/hngprojects/hng_boilerplate_nextjs/issues) for easy location,