Feat/hng 150 add product modal
hngprojects/hng_boilerplate_nextjs pull request #368
Opened 2024-07-20 15:12 UTC by Bwesun

# Description

**Closes #150**

# Changes proposed

## What were you told to do?
[FEAT] Super Admin Add Products Modal Component https://github.com/hngprojects/hng_boilerplate_nextjs/issues/150

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-07-20 19:35 UTC, Justfemi requested changes

2024-07-20 19:35 UTC, Justfemi commented on src/components/ui/textarea.tsx
> +import * as React from "react"
Import React from react

2024-07-20 19:35 UTC, Justfemi commented on src/components/ui/label.tsx
> +import * as React from "react"
Import React from "react" and not "* as React..."

2024-07-20 19:35 UTC, Justfemi commented on src/components/AddProduct/index.tsx
> +import {
Move the content of this file to the src/components/modals/AddProduct.tsx file

2024-07-20 19:35 UTC, Justfemi commented on src/components/AddProduct/index.tsx
> +import { Input } from "../ui/input";
Use ~ for all import (button, input, text area ....) and not relative path

2024-07-20 19:35 UTC, Justfemi commented on package.json
Don't edit this file, all you need have been installed. 
If need any package that hasn't been installed, reach out on slack.

2024-07-20 20:47 UTC, oreoluwa212 commented
`
This branch has conflicts that must be resolved
 to resolve conflicts before continuing.
Conflicting files
package.json
pnpm-lock.yaml
src/app/page.test.tsx
src/app/page.tsx
src/components/modals/PasswordSuccessfulModal/PasswordSuccessfulModal.test.tsx
src/components/modals/PasswordSuccessfulModal/PasswordSuccessfulModal.tsx
src/components/ui/dialog.tsx
src/components/ui/input.tsx
src/components/ui/label.tsx
src/components/ui/textarea.tsx
`

2024-07-21 07:20 UTC, Bwesun commented
Please there are files that i have not editted or done anything to. like the first 2 files. the first reviewer said i shouldn't edit the file. furthermore, the rest of the files aren't what i did. i know nothing about them. How do i resolve their conflicts.

2024-07-22 08:52 UTC, skeby commented
> Please there are files that i have not editted or done anything to. like the first 2 files. the first reviewer said i shouldn't edit the file. furthermore, the rest of the files aren't what i did. i know nothing about them. How do i resolve their conflicts.

pull from dev, accept all incoming for those files

2024-07-28 14:14 UTC, closed without merging