Feat/HNG-177: Implement Custom Textarea with Validation and Character Count
hngprojects/hng_boilerplate_nextjs pull request #371
Opened 2024-07-20 15:45 UTC by JoshuaAkpan

# Description

**Closes #177  **

# Changes proposed

## What were you told to do?

https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=10-16395&t=ZQNRsvC3jgSF9JiA-1

Develop a Textarea with Character Limit component.

## What did you do?

1. Created the CharacterLimitTextarea component.
- Props include maxLength, value, onChange, id, name, and label.
- Tracks character count and handles errors when the character limit is exceeded.
- Displays the character count and error messages conditionally.

2. Implemented the useCharacterLimit custom hook.
- Manages character count and error state.
- Updates state based on the current value and maxLength.

3. Added unit tests in CharacterLimitTextarea.test.tsx.
- Tests for rendering, character count updates, and error message display.
- Ensures onChange callback is correctly triggered.

4. Added index.tsx for easy import of the CharacterLimitTextarea component.

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos

![Initial State](https://github.com/user-attachments/assets/acd12e85-6a29-40ca-b871-c7f72aa9b4d1)

![Character Count Updating](https://github.com/user-attachments/assets/74cf0fb4-adba-4ae9-a7e5-1926790586d4)

![Error Message](https://github.com/user-attachments/assets/b1216050-e02e-42e2-a70d-570222069bb2)

![Lint PASS](https://github.com/user-attachments/assets/48eca3ce-d044-4943-81ec-74028f899a6d)

2024-07-20 15:49 UTC, PrudentBird approved these changes

2024-07-20 15:49 UTC, PrudentBird commented
Resolve merge conflicts and we good to go

2024-07-20 17:56 UTC, JulianaSau commented
why are you force pushing changes?

2024-07-20 18:13 UTC, JoshuaAkpan commented
> why are you force pushing changes?
@JulianaSau 

Hi Juliana,

Thank you for your review and for raising this question. I performed a force push to update the remote branch with the latest changes after rebasing my branch onto the main branch. Here’s a brief overview of why this was necessary:

Rebasing for a Clean History: To ensure a clean and linear commit history, I rebased my branch `feat/HNG-177-implement-custom-textarea-with-validation-and-character-count` onto the latest main branch. Rebasing rewrites the commit history to incorporate upstream changes and resolve conflicts in a cleaner manner.

Resolving Conflicts: During the rebase, I encountered and resolved merge conflicts. Since rebasing modifies commit history, a force push was required to update the remote branch with these new changes.

Maintaining Consistency: Force pushing was essential to ensure that the remote branch reflects the updated commit history accurately and aligns with the changes made during the rebase process.

I understand the importance of coordinating such actions, and I have verified that no other changes were lost or overwritten in the process. If there are any concerns or additional questions, please let me know, and I’d be happy to address them.

Thank you for your understanding.

Best regards,
Joshua

2024-07-20 20:27 UTC, oreoluwa212 requested changes
You have a conflicting file, pull from upstream and merge up. Put your component at the bottom. Also, images should not be in any html folder but public....public > images > yourpagename
```
[Conflicting files
src/app/guides/page.tsx]
```

2024-07-20 21:28 UTC, oreoluwa212 commented
```
This branch has conflicts that must be resolved (https://github.com/hngprojects/hng_boilerplate_nextjs/pull/371/conflicts) or the  to resolve conflicts.
Conflicting files
src/app/guides/page.tsx
```

2024-07-20 21:34 UTC, oreoluwa212 requested changes, later dismissed
Proper folder structure accepted here for images 

public > images > yourpagename

What do you mean index.html?? Remove that thing you put in the page.tsx, you're 2orking on just ackmponent that is to be used by others. Why will you not use shadcn to get the textarea and then create your subfolders inside the componemts/common to house any file concerning your task

2024-07-20 21:34 UTC, oreoluwa212 commented on src/test/CharacterLimitTextarea.test.tsx
> +
Remove comments

2024-07-20 21:34 UTC, oreoluwa212 commented on src/app/guides/page.tsx
To save yourself, pull from upstream and for this page, accept incoming changes because the page to be rendered at / already is here on the repo

2024-07-20 23:28 UTC, PrudentBird requested changes
Go and do the needful

2024-07-21 00:17 UTC, JoshuaAkpan commented
> You have a conflicting file, pull from upstream and merge up. Put your component at the bottom. Also, images should not be in any html folder but public....public > images > yourpagename
> 
> ```
> [Conflicting files
> src/app/guides/page.tsx]
> ```

@oreoluwa212 

I didn't work with image in my project, I only worked on the component, the test file and the page.tsx.

2024-07-21 02:44 UTC, JoshuaAkpan commented
Hi @PrudentBird  and @oreoluwa212,

I have addressed the feedback provided and resolved the conversations. Could you please review the changes when you have a moment?

Thank you!
Joshua

2024-07-21 05:45 UTC, PrudentBird approved these changes

2024-07-21 05:48 UTC, PrudentBird approved these changes

2024-07-21 05:49 UTC, merged