Feat/29 Create a Member Card Component for Dashboard
hngprojects/hng_boilerplate_nextjs pull request #374
Opened 2024-07-20 16:21 UTC by Saviourise

# Description

**Closes #14**

# Changes proposed

## What were you told to do?

Create a Member Card Component for Dashboard

## What did you do?

1. I created a member card component for dashboard
2. I added neccesary props so that the component can be fully dynamic
3. I followed design implementation and made sure the card is responsive
4. I used shadcn for select and dropdown
5. I tested the component to make sure it is working

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

![Screenshot 2024-07-20 170247](https://github.com/user-attachments/assets/8650d52d-1ab7-407d-bc4c-85c168dde4f6)
![Screenshot 2024-07-20 171448](https://github.com/user-attachments/assets/8b4d5646-b088-4442-9b49-edbb4b671db7)

2024-07-20 18:08 UTC, skeby commented on src/components/common/DashboardMemberCard/index.css
You were told not to create your own css files
Use tailwind boss

2024-07-20 18:10 UTC, skeby requested changes
Attach screenshots of the stuff you built

2024-07-20 18:48 UTC, saviour-encentral commented on src/components/common/DashboardMemberCard/index.css
I added CSS because what I was trying to achieve was not available on tailwind

2024-07-21 04:50 UTC, skeby commented on src/components/common/DashboardMemberCard/index.css
I don't understand?
What happened to `font-medium text-sm text-[#0f172a]`

2024-07-21 07:51 UTC, saviour-encentral commented on src/components/common/DashboardMemberCard/index.css
I have removed the file @skeby , that is why I said you should review again

2024-07-21 07:51 UTC, saviour-encentral commented on src/components/common/DashboardMemberCard/index.css
I have removed the file @skeby , that is why I said you should review again

2024-07-21 08:05 UTC, closed without merging