Feat/hng 26 currency formater component
hngprojects/hng_boilerplate_nextjs pull request #402
Opened 2024-07-20 19:06 UTC by Amdragz

# Description
This PR addresses the issue by implementing a Currency Converter component which allows users to convert an amount from USD to various currencies and display the converted amount with the appropriate currency symbol.

**Closes #issue_number_here**
Closes #26

# Changes proposed

## What were you told to do?
 Implement a reusable Currency Formatter component 
The task was to develop a Currency Converter component that takes an amount, showSymbol and a currency code as props, and converts the amount according to the currency and then render the amount and if showSymbol is passed render the currency symbol on the screen

## What did you do?
Implemented the Currency Converter component.
Added fetchRates function to retrieve conversion rates from the API.
Integrated convertCurrencyFromUSD function to perform currency conversion.
Managed component states for loading, error handling, and displaying the result.
Added unit tests to cover the  successful data fetching, and conversion calculations.

I created the component under the common component, i created the currency converter component and two unit test files for it, i implemented the currency converter component by fetching the exchange rate for the currencies from a free API site and use the rate to carryout a simple calculation in a convertCurrencyyFromUSD function. Then i wrote test to test my functions and what would happen for different edge cases, i did not change any files and i did basic styling with tailwind css

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos
[2024-07-20 19-57-33.zip](https://github.com/user-attachments/files/16322078/2024-07-20.19-57-33.zip)

2024-07-20 21:39 UTC, oreoluwa212 commented on src/components/common/CurrencyConverter/index.tsx
> +
This whole block, remove it, thank you

Logging to the console is generally prohibited in this stage. Thanks again

So, I see potential here but please you remember stage 2 bah, static just static,  dont overdo. Thanks 

Waiting for your kind corrections. I need a video of you testing your component

Add screenshots to your pnpm test and lint test. Thanksssss

2024-07-20 21:39 UTC, oreoluwa212 requested changes
...thank....you

2024-07-21 10:38 UTC, Amdragz commented
I have refactored the code to remove any instance of console.logs, i made the fetchRate function return some mock conversion rates instead of logging errors 
[HNG-#26-test.zip](https://github.com/user-attachments/files/16323896/HNG-.26-test.zip)
[HNG-test-26-take-2 2024-07-21 113607.zip](https://github.com/user-attachments/files/16323912/HNG-test-26-take-2.2024-07-21.113607.zip)

2024-07-22 13:24 UTC, Amdragz commented
Please merge my branch I have reviwed and made the requested changes

On Sat, Jul 20, 2024, 10:40 PM oreoluwa212 ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> ...thank....you
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/hngprojects/hng_boilerplate_nextjs/pull/402#pullrequestreview-2190064201>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BFPO6N2ODFU7IGF742SUGBDZNLKLHAVCNFSM6AAAAABLGFCK2OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDCOJQGA3DIMRQGE>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-07-28 14:14 UTC, closed without merging