feat: implement login with magic link
hngprojects/hng_boilerplate_nextjs pull request #438
Opened 2024-07-21 01:57 UTC by iamExony

# Description
Implement the Login with magic link page

**Closes #18**

# Changes proposed

## What were you told to do?
I was instructed to implement a responsive login page with a magic link feature, write tests for the code, and use components where necessary (such as the header, footer, buttons, and modal).
Figma Design:
https://www.figma.com/design/VEItfX6St5NSAqqNHImcxD/HNG-Boilerplate-Designs?node-id=2-868&t=mpiMe1cp8NXRwgLd-0

[FEAT] - Authentication Page -> Login with magic link 

## What did you do?

- Implementatd a magic login
- Add Email validation to check valid email address
- Tested my code using vitest with a pass
- My codes has no ESLint errors
- Complemented a responsive design on mobile, desktop and tablet screens
- Ensure the UI matches with the figma design

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x ] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos
![image](https://github.com/user-attachments/assets/91ec6b02-e9b1-4c3e-99b7-f137bc7d71b0)
![image](https://github.com/user-attachments/assets/4faf467d-44ce-4129-89e5-247036eb988e)
![Lintest](https://github.com/user-attachments/assets/857b360e-2bb1-482a-8743-f1c70638c31f)
![test](https://github.com/user-attachments/assets/0e02a529-ba00-4d93-904a-88a0b0c91c06)
![testfull](https://github.com/user-attachments/assets/2c185200-4d06-4b7e-8fa3-63110225b083)

2024-07-21 12:48 UTC, Justfemi requested changes

2024-07-21 12:48 UTC, Justfemi commented on src/components/common/MagicLogin/MagicLogin.tsx
Your file shouldn't be in this directory, add it to the auth folder please

2024-07-21 22:24 UTC, oreoluwa212 approved these changes
reviewed

2024-07-21 23:45 UTC, iamExony commented
> move your folder into the appropriate folder as stated

I checked folders i didnt see auth folder, i created one in the app folder and placed it there

2024-07-22 09:48 UTC, JulianaSau commented
your lint tests are failing

2024-07-22 11:42 UTC, iamExony commented
> your lint tests are failing

Ma the lint test passed, the vitest failed not from my own task but someone elses task. the page.tsx from someone else mine passed correctly. mine is Login.tsx

2024-07-22 15:20 UTC, mrcoded approved these changes

2024-07-22 15:21 UTC, mrcoded requested changes
move this file to the auth folder @iamExony

2024-07-22 15:49 UTC, mrcoded approved these changes

2024-07-22 15:49 UTC, merged