Feat/84 implement subscription and plan overview page
hngprojects/hng_boilerplate_nextjs pull request #456
Opened 2024-07-21 07:35 UTC by Emmadegreat

<img width="362" alt="eslint-test" src="https://github.com/user-attachments/assets/93ad0681-bc8d-423f-82fe-ab5c610c20ad">
<img width="647" alt="vitest-test-for-stage4-task" src="https://github.com/user-attachments/assets/2560d8ee-d7e3-486c-ac84-a4c4bc03417d">
<img width="903" alt="Stage4-vitest-test" src="https://github.com/user-attachments/assets/8171fca1-6ba3-4c1e-af2e-aff55bdd806f">

# Description

**Implement Subscription and Plan Overview Page: #84 **

# Changes proposed

## What were you told to do?
Set up the Subscription and Plan Overview page component.
Fetch and display current subscription plan details from the backend.
Add detailed information about the current plan (benefits, project management, sharing and collaboration, management and security, supports).
Implement options for users to upgrade to Advanced or Premium plans.
Add functional Cancel and Upgrade buttons.
Implement option for users to cancel their subscription.
Integrate with the backend API for fetching plan details and handling upgrades/cancellations.
Add form validation for any required inputs.
Implement error handling and display of error messages.
Ensure the page is responsive across all devices.
Write unit tests for key functionalities.
Conduct integration tests with the backend.
Perform manual testing for responsiveness and accessibility.

Implement Subscription and Plan Overview Page

## What did you do?
I created the subscription and plan overview page according to the design.
Though the tablet and mobile view was not provided in the design, but I ensured that the page is responsive, across different screen sizes.
Used dummy data to display the expected user data.

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [ ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-07-21 11:04 UTC, oreoluwa212 requested changes
Your work is almost done
But
1. Dont you need header and footer for this page? (Please attach a video of you routing to your page on localhost) 
2. If you need the layout.tsx you just need to copy the one from (home) and put in your sub & plan folder

2024-07-21 15:21 UTC, Emmadegreat commented
https://github.com/user-attachments/assets/caf8abcc-00fd-4126-b297-5891d3851af3

Updated

Video:

2024-07-22 02:21 UTC, Emmadegreat commented
I have made the recommended corrections, and attached the task page Figma link and screenshot of the page.
Kindly merge my pull request.

2024-07-22 14:37 UTC, mrcoded approved these changes

2024-07-22 14:37 UTC, merged