Feat/hng 102 subscription renewal reminder template
hngprojects/hng_boilerplate_nextjs pull request #536
Opened 2024-07-21 19:47 UTC by callmestiles

# Description

Closes #102 

# Changes proposed

## What were you told to do?

Create a Subscription Renewal Reminder email template according to the design using React Email

## What did you do?

Added a new folder to the email templates and created a new email template there with react-email. Also added a test for the email template in the test folder.

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos

![screencapture-localhost-3000-preview-subscription-renewal-reminder-Subscription-2024-07-21-19_42_36](https://github.com/user-attachments/assets/2dd324a5-5001-4269-85b2-255d295141e6)
![image](https://github.com/user-attachments/assets/ae53064d-a07b-4294-9318-699b49ca0caa)
![image](https://github.com/user-attachments/assets/262d40a7-c000-49e1-8487-51ac42416917)

2024-07-21 20:34 UTC, oreoluwa212 requested changes
Follow Camel case convention for your file names, pull from upstream and ensure all tests passed

2024-07-21 21:36 UTC, callmestiles commented
> Follow Camel case convention for your file names, pull from upstream and ensure all tests passed

done

2024-07-22 00:14 UTC, abiona01 requested changes, later dismissed

2024-07-22 00:14 UTC, abiona01 commented on src/email/templates/subscriptionRenewalReminder/with-image.tsx
> +import {
File name is not in camel case

2024-07-22 03:20 UTC, callmestiles commented on src/email/templates/subscriptionRenewalReminder/with-image.tsx
> +import {
Fixed

2024-07-22 03:43 UTC, oreoluwa212 approved these changes

2024-07-22 03:45 UTC, merged