78 feat super admin dashboard page
hngprojects/hng_boilerplate_nextjs pull request #541
Opened 2024-07-21 20:08 UTC by wunmicrown

# Description
**Closes #78**

# Changes proposed

## What were you told to do?

**Use existing card, charts and products components for consistency.
Ensure all components match the design specifications provided.
Design Specifications:

**Refer to the provided design for dimensions, colors, and layout.
Include all items and interactions as designed
Functionality:

**put together all existing components to make up the admin dashboard page
**Accessibility: Ensure all components are accessible and follow best practices
**Testing: Ensure the component renders correctly with all required elements.

## What did you do?
# Admin Dashboard

## Requirements

### Use Existing Components
- Use existing card, charts, and products components for consistency.

### Design Specifications
- Refer to the provided design for dimensions, colors, and layout.
- Include all items and interactions as designed.

### Functionality
- Put together all existing components to make up the admin dashboard page.

### Accessibility
- Ensure all components are accessible and follow best practices.

### Testing
- Ensure the component renders correctly with all required elements.

## Implementation

### What did you do?

#### Client Component
- Created a client-side component for the admin dashboard.

#### Components Used
- **CardComponent**: To display card data.
- **Chart**: To display chart data.
- **TopProductsComponent**: To display top products data.

#### Data Imported
- **cardData**: For card details.
- **chartData** and **chartConfig**: For chart details.
- **data** and **gradients**: For top products details.

#### Design
- The section is styled with Tailwind CSS.
- Used a grid layout for cards with responsiveness.
- Used a flexbox layout for chart and top products with responsiveness.

### Accessibility
- Ensured all components are accessible and follow best practices.

### Testing
- Ensured the component renders correctly with all required elements.
- Wrote tests using `@testing-library/react` and Vitest.
- Stored tests in the `test/adminDashboard` subfolder.
- Included `expect.hasAssertions()` in the tests.
- Used `vi` from Vitest for mocking functions.

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x ] This PR does not contain plagiarized content.
- [x ] The title and description of the PR is clear and explains the approach.
- [ x] I am making a pull request against the **dev branch** (left side).
- [x ] My commit messages styles matches our requested structure.
- [x ] My code additions will fail neither code linting checks nor unit test.
- [ x] I am only making changes to files I was requested to.

# Screenshots/Videos
![dashboard](https://github.com/user-attachments/assets/ed1ed61d-93a0-457a-92a2-5bb1b03e4ed2)

2024-07-21 20:38 UTC, oreoluwa212 requested changes
All tests failed, pull from upstrean and fix

2024-07-21 20:44 UTC, oreoluwa212 requested changes
Fix all tests fails and attach screenshots and video of how your component works

2024-07-21 20:48 UTC, oreoluwa212 commented
Most of the components on your issue are already existing, check the user dashboard page for reference to these components
i.e just a single file calling this component and your test file

2024-07-22 18:51 UTC, mrcoded approved these changes

2024-07-22 18:51 UTC, merged