Feat/HNG 113 create related articles on dynamic blog page
hngprojects/hng_boilerplate_nextjs pull request #552
Opened 2024-07-21 21:53 UTC by Kored28

# Description

**Closes #113**

# Changes proposed

## What were you told to do?
Implement the design for the related article in the dynamic blog detail page

[FEATURE] Create and implement the API integration for Related Articles on the dynamic blog page

## What did you do?

- I implemented all the sections in the design
- I made the component responsive
- I made use of reusable components where needed
- I wrote test for the implementations
- I made sure I used proper commit message

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos
Design
![Screenshot (8)](https://github.com/user-attachments/assets/c76e00ac-e2fb-42b2-8eb4-add3c5840031)
![Screenshot (9)](https://github.com/user-attachments/assets/e6380ee9-003c-43a2-9fdf-9e0a632aa454)

Implementation
![Screenshot (6)](https://github.com/user-attachments/assets/ad9ea490-40cd-4a28-8368-8c9a41854046)
![Screenshot (7)](https://github.com/user-attachments/assets/041c8886-46d3-438c-8443-63d53f11f17f)

Testing
![Screenshot (11)](https://github.com/user-attachments/assets/26baf98e-603f-4ff7-83c5-5c81e0f36a0e)
![Screenshot (12)](https://github.com/user-attachments/assets/886c7293-ee4f-4ec7-9a44-370dc6c86129)

Proof the test worked
![Screenshot (16)](https://github.com/user-attachments/assets/bf0df270-e1d1-4c26-a34b-525a5f328e4b)

2024-07-21 21:54 UTC, Kored28 commented
There was no custom color that matched the color in the design

2024-07-22 08:17 UTC, JulianaSau requested changes

2024-07-22 08:17 UTC, JulianaSau commented on tailwind.config.ts
These changes seem very unnecessary. remove them

2024-07-22 08:17 UTC, JulianaSau commented on src/test/Button.test.tsx
same to the changes here

2024-07-22 08:17 UTC, JulianaSau commented on src/components/blog/BlogCard.tsx
> +            <p className="text-[14px] font-normal text-[#525252]">
for the colors, if they dont exist, add them to the tailwind config. dont use custom colors

2024-07-22 08:17 UTC, JulianaSau commented on src/app/globals.css
these changes seem unnecessary

2024-07-22 08:17 UTC, JulianaSau commented on src/app/favicon.ico
why did you delete this?

2024-07-22 08:17 UTC, JulianaSau commented on src/app/blog/Blog.tsx
what does this page do?
Doesnt seem to be used anywhere

2024-07-22 08:54 UTC, Kored28 commented on src/app/globals.css
It was what I pulled from upstream yesterday

2024-07-22 08:54 UTC, Kored28 commented on src/components/blog/BlogCard.tsx
> +            <p className="text-[14px] font-normal text-[#525252]">
Okay

2024-07-22 08:55 UTC, Kored28 commented on src/app/favicon.ico
It was what I pulled from upstream yesterday

2024-07-22 08:56 UTC, Kored28 commented on src/app/blog/Blog.tsx
I used it so I could see what I was doing on the local Host. I will remove it

2024-07-22 09:15 UTC, Kored28 commented on tailwind.config.ts
It is because of the pull from stream I made yesterday

2024-07-22 10:54 UTC, closed without merging