Feat:created the implemented the payment page  Team-starlight
hngprojects/hng_boilerplate_nextjs pull request #720
Opened 2024-07-29 10:19 UTC by jerahmeel200

# Description

**Closes #issue_number_here**

# Changes proposed

## What were you told to do?

## What did you do?

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [ ] My code follows the code style of this project.
- [ ] This PR does not contain plagiarized content.
- [ ] The title and description of the PR is clear and explains the approach.
- [ ] I am making a pull request against the **dev branch** (left side).
- [ ] My commit messages styles matches our requested structure.
- [ ] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-07-29 15:30 UTC, jerahmeel200 reviewed
made some changes

2024-07-29 16:50 UTC, jerahmeel200 reviewed
made some changes

2024-07-30 10:03 UTC, jerahmeel200 commented
phoenix abeg run this merge

2024-07-30 10:07 UTC, PrudentBird requested changes
Why are you putting page content in a component??

2024-07-30 12:32 UTC, jerahmeel200 commented
but it is a component foe that particular  page

2024-07-30 13:00 UTC, PrudentBird requested changes

2024-07-30 13:00 UTC, PrudentBird commented on git
What file is this 

Kindly remove

2024-07-30 13:05 UTC, jerahmeel200 commented on git
what file?

2024-07-30 13:06 UTC, PrudentBird commented on git
It's a folder or whatever it is

2024-07-30 15:07 UTC, closed without merging