Feat/hng create edit product detail page team kimiko
hngprojects/hng_boilerplate_nextjs pull request #769
Opened 2024-07-30 10:24 UTC by abanicaisse

# Description
Create a new page where superadmin can view and and edit a particular product details, as implemented on the new design changes

**Closes #issue_number_here**

# Changes proposed
- New superadmin route at **/dashboard/admin/products/edit/{product-id}**
- Different inputs to allow super-admin to easily edit a given product detail

## What were you told to do?
- Create edit product details page for superadmin
- Ensure the page is responsive and consistent accross multiple screen sizes
- Ensure the changes proposed pass all the different tests

## What did you do?
- Create new "edit product detail page" at route **/dashboard/admin/products/edit/{product-id}**
- Add upload product pictures functionality
- Create all different inputs to allow superadmin easily edit product page

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [ ] I am only making changes to files I was requested to.

# Screenshots/Videos
<img width="1440" alt="Screenshot 2024-07-30 at 13 20 13" src="https://github.com/user-attachments/assets/d1f710e9-0ce0-4b06-8d6c-fab27857178b">
<img width="336" alt="Screenshot 2024-07-30 at 13 21 48" src="https://github.com/user-attachments/assets/a73a02dc-b0c9-42b1-be4b-01ec7c6d59a9">

2024-07-30 12:17 UTC, prudentbird requested changes

2024-07-30 12:17 UTC, PrudentBird commented on src/app/dashboard/(admin)/admin/products/_components/ProductTable/product-table.tsx
Remove totally, don't make comments

2024-07-30 12:18 UTC, abanicaisse commented on src/app/dashboard/(admin)/admin/products/_components/ProductTable/product-table.tsx
okay boss

2024-07-30 20:03 UTC, Justfemi approved these changes, later dismissed

2024-07-31 06:18 UTC, PrudentBird approved these changes, later dismissed

2024-07-31 09:19 UTC, closed without merging