feat: implemented functionality to add a profile picture by saving to…
hngprojects/hng_boilerplate_nextjs pull request #963
Opened 2024-08-12 07:15 UTC by Maiqel1

# Description

This PR addresses the issues with fetching and updating the user's profile image from the backend rather than the session. It includes enhancements to ensure the profile image URL is correctly fetched and uploaded using the base API URL.

# Changes proposed

- Update the profile image fetching mechanism to use the backend API instead of the session.
- Ensure the image upload API correctly handles the base URL.

## **What did you do?**

- Modified the API calls to fetch the profile image from the backend using the base URL.
- Implemented error handling for unauthorized requests during image upload and profile data fetching.
- Updated the image upload process to ensure the correct URL is used.

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-08-12 07:55 UTC, incredible-phoenix246 requested changes

2024-08-12 07:55 UTC, incredible-phoenix246 commented on src/app/dashboard/(admin)/admin/(settings)/settings/page.tsx
> +          const profilePicUrl = uploadData.data.profile_picture_url.replace('http://localhost:3009', baseUrl);
Why 😭😭

2024-08-12 07:55 UTC, incredible-phoenix246 commented on src/config/auth.config.ts
no brother nobody is touching this

all teams are to use avatar_url

2024-08-12 07:55 UTC, incredible-phoenix246 commented on src/lib/auth.ts
very very very wrong

2024-08-12 07:55 UTC, incredible-phoenix246 commented on src/types/index.d.ts
nope

2024-08-12 07:57 UTC, incredible-phoenix246 commented on src/app/dashboard/(admin)/admin/(settings)/settings/page.tsx
> +        const UPLOAD_API_URL = `${baseUrl}/api/v1/profile/upload-image`;
concerning this which team are you we need to talk about this

2024-08-12 07:57 UTC, incredible-phoenix246 requested changes
also fix you lint issues

2024-08-12 20:36 UTC, incredible-phoenix246 requested changes

2024-08-12 20:36 UTC, incredible-phoenix246 commented on src/app/dashboard/(admin)/admin/(settings)/settings/page.tsx
> +      await signIn("credentials", { redirect: false });
Sign-in again how

2024-08-12 20:36 UTC, incredible-phoenix246 commented on src/app/dashboard/(admin)/admin/(settings)/settings/page.tsx
> +import { signIn, useSession } from "next-auth/react";
use the unstable_update

now imagine it is a google user how will you authenticate the user

2024-08-12 20:36 UTC, incredible-phoenix246 commented on src/app/dashboard/(admin)/admin/(settings)/settings/page.tsx
> +      await signIn("credentials", { redirect: false });
credential sign bro

2024-08-13 07:04 UTC, PrudentBird submitted a review, later dismissed

2024-08-13 07:09 UTC, PrudentBird commented
Use avatar_url instead of profile pic URL

2024-08-13 10:54 UTC, incredible-phoenix246 approved these changes, later dismissed

2024-08-13 11:24 UTC, chumex412 approved these changes, later dismissed

2024-08-13 11:47 UTC, Maiqel1 commented
one last time, i had lint errors @incredible-phoenix246 😭😭😭😭😭😭

2024-08-13 12:17 UTC, chumex412 approved these changes

2024-08-13 12:27 UTC, oreoluwa212 approved these changes

2024-08-13 12:41 UTC, merged