fix: Cannot read properties of undefined
hngprojects/hng_boilerplate_nextjs pull request #964
Opened 2024-08-12 22:41 UTC by sim-codes

# Description

**Closes #issue_number_here**

# Changes proposed

## What were you told to do?

## What did you do?

Fixed `Cannot read properties of undefined` causing error on user signin
# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-08-12 23:20 UTC, incredible-phoenix246 submitted a review, later dismissed

2024-08-13 07:27 UTC, PrudentBird requested changes

2024-08-13 07:27 UTC, prudentbird commented on src/app/(auth-routes)/login/page.tsx
User should always have an organization, and instead of preventing the codeblock from executing, use error handling to manage it

2024-08-13 07:32 UTC, sim-codes commented on src/app/(auth-routes)/login/page.tsx
My thought was first time users should be able to sign in without organisation, organisation is not included in the data sent by the endpoint on user sign in

2024-08-13 07:33 UTC, PrudentBird commented on src/app/(auth-routes)/login/page.tsx
Go and meet your backend devs

User must have organization at all times !

2024-08-13 07:34 UTC, PrudentBird commented
PR Title is generic

2024-08-13 07:35 UTC, Homoakin619 commented on src/app/(auth-routes)/login/page.tsx
"organisations" is returned as part of the authentication response payload which contains an array of user's organisations

2024-08-13 10:01 UTC, kiisi approved these changes

2024-08-13 10:02 UTC, kiisi submitted a review, later dismissed

2024-08-14 09:23 UTC, PrudentBird approved these changes

2024-08-15 12:21 UTC, PrudentBird approved these changes

2024-08-15 19:02 UTC, incredible-phoenix246 approved these changes

2024-08-25 18:34 UTC, closed without merging