Feat/multiple languages support
hngprojects/hng_boilerplate_nextjs pull request #965
Opened 2024-08-13 06:34 UTC by chiefEbube

# Description
Implement the UI for multiple language support (English, French, Spanish) within the BOILERPLATE. This involves integrating a language selection feature into the navigation bar for quick access and ensuring that users can also change their preferred language via the settings page. The selected language should be consistently applied across all frontend components, and the interface must be fully mobile responsive.

**Closes #issue_number_here**

# Changes proposed

## What were you told to do?
- **Implement Language Selection Interface:**

Implement the UI for a language selection feature within the navigation bar, ensuring it is easily accessible and allows users to quickly switch between EN, FR, and ES.

Develop a secondary language selection interface on the settings page, providing an alternative option for users to change their preferred language.

Ensure both interfaces are intuitive and maintain consistency with the overall BOILERPLATE design.

- **Consistent Language Application:**

Implement a localization library (e.g., i18n, react-intl) to manage and apply translations across all frontend components.

Ensure that all text elements, including headings, labels, buttons, and notifications, reflect the selected language throughout the application.

Implement fallback mechanisms to handle cases where translations may be missing or incomplete.

- **Mobile Responsiveness:**

Ensure the language selection interfaces and all UI elements are fully mobile responsive, maintaining usability and visual consistency across various screen sizes and orientations.

Implement responsive design practices to ensure the interface adapts smoothly when switching languages or resizing screens.

+ **Documentation and Best Practices:**

Research available documentation on best practices for implementing multilingual support in web applications.

Follow coding standards and best practices for internationalization and localization to ensure maintainability and scalability.

## What did you do?

- My PR is a successful attempt to fulfill the above requirements.
# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [X] My code follows the code style of this project.
- [X] This PR does not contain plagiarized content.
- [X] The title and description of the PR is clear and explains the approach.
- [X] I am making a pull request against the **dev branch** (left side).
- [X] My commit messages styles matches our requested structure.
- [X] My code additions will fail neither code linting checks nor unit test.
- [X] I am only making changes to files I was requested to.

# Screenshots/Videos
![IMG-20240813-WA0004](https://github.com/user-attachments/assets/ebb992b1-0d48-42f1-978a-2da6efca9ba5)
![IMG-20240813-WA0006](https://github.com/user-attachments/assets/4f72099b-bbfd-4444-997a-8f5f2a202a52)

2024-08-13 07:29 UTC, PrudentBird commented
Your commit messages are wrong

You have lint errors

2024-08-13 07:32 UTC, PrudentBird requested changes

2024-08-13 07:32 UTC, PrudentBird commented on public/images/flags/en.svg
Use an icon library!

2024-08-13 07:32 UTC, PrudentBird commented on messages/fr.json
Why supporting only 3 languages?

2024-08-13 07:32 UTC, PrudentBird commented on src/i18n.ts
This file name isn't valid!

2024-08-13 09:44 UTC, chiefEbube commented on messages/fr.json
I'm supporting 3 languages because that's exactly what is in the linear ticket.

2024-08-13 09:45 UTC, chiefEbube commented on src/i18n.ts
Then this file name is coming from the library. It's not a custom name I just gave to the file.

2024-08-13 09:46 UTC, chiefEbube commented on public/images/flags/en.svg
I'll check if this is possible and fix it.

2024-08-13 18:06 UTC, chiefEbube commented
@PrudentBird, I have resolved the lint issues. But I can't use icons for the flags because lucide-react doesn't have that and also, I can't change i18n.ts file name because it comes with the next-int'l library

2024-08-13 18:34 UTC, PrudentBird submitted a review, later dismissed

2024-08-14 14:54 UTC, PrudentBird approved these changes

2024-08-14 14:56 UTC, incredible-phoenix246 approved these changes

2024-08-14 14:58 UTC, merged