update the endpoint format change from the backend
hngprojects/hng_boilerplate_nextjs pull request #967
Opened 2024-08-13 15:54 UTC by Wheezy049

# Description
I updated my  endpoint format from /api/v1/newsletters/subscription to /api/v1/newsletter-subscription because it was change on the backend staging url

**Closes #issue_number_here**

# Changes proposed

## What were you told to do?
To update newsletter-subscription endpoint url format

## What did you do?
I update newsletter-subscription endpoint url format

# Check List (Check all the applicable boxes)

🚨Please review the [contribution guideline](CONTRIBUTING.md) for this repository.

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR is clear and explains the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit messages styles matches our requested structure.
- [x] My code additions will fail neither code linting checks nor unit test.
- [x] I am only making changes to files I was requested to.

# Screenshots/Videos

2024-08-13 16:04 UTC, incredible-phoenix246 requested changes

2024-08-13 16:04 UTC, incredible-phoenix246 commented on src/components/layouts/footer/index.tsx
> +        `${apiUrl}/api/v1/newsletter-subcription`,
subscription not subcription

2024-08-13 17:08 UTC, Wheezy049 commented
Dont merge this

2024-08-13 17:08 UTC, Wheezy049 commented on src/components/layouts/footer/index.tsx
> +        `${apiUrl}/api/v1/newsletter-subcription`,
already see it

2024-08-13 20:29 UTC, incredible-phoenix246 approved these changes

2024-08-14 09:21 UTC, PrudentBird approved these changes

2024-08-14 10:24 UTC, Samadeen approved these changes

2024-08-14 10:25 UTC, merged